### ISSUE TITLE
参考书

### ISSUE THREAD

**Issue by zxuanyu** [YiChenLai/Sequencial_Optical_System_Simulation#2]
你好，看了你的代码很受启发，但是有写代码看不懂，请问opd lsf psf mtf和ray trace的参考书用的哪本？谢谢

**Comment by YiChenLai** [comment]
你好 ! 幾何光學的部分主要是參考 Pedrotti 的 Introduction To Optics Third Edition，而傅氏光學是參考 Goodman 的 Introduction to Fourier Optics。
